### ISSUE TITLE
Issue with type resolution 

### ISSUE THREAD

**Issue by bryevdv** [felix-hilden/sphinx-codeautolink#120]
### Issue
When building the Bokeh docs, things expode:
```
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/site-packages/sphinx_codeautolink/extension/__init__.py", line 42, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/site-packages/sphinx_codeautolink/extension/__init__.py", line 176, in create_references
    self.filter_and_resolve(transforms, skipped, doc)
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/site-packages/sphinx_codeautolink/extension/__init__.py", line 200, in filter_and_resolve
    key = resolve_location(name, self.inventory)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/site-packages/sphinx_codeautolink/extension/resolve.py", line 36, in resolve_location
    cursor = locate_type(cursor, tuple(comps), inventory)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bryan/anaconda/envs/dev-311/lib/python3.11/site-packages/sphinx_codeautolink/extension/resolve.py", line 92, in locate_type
    for val in previous.value.mro():
               ^^^^^^^^^^^^^^^^^^^^
TypeError: unbound method type.mro() needs an argument
```
The proximate cause turns out to be that `previous.value` is `builtins.type` at this point:
```
(Pdb) previous
Cursor(location='builtins.type', value=<class 'type'>, instance=False)
```
Bokeh is a cross-runtime library and uses a fair amount of meta-programming to automate management of that complexity. That might be why this unexpected values ends up here. 

### Expected behavior

Completed  successful build

### Steps to reproduce

I am a maintainer for Bokeh and encountered this while building the Bokeh docs. I am afraid I have not been able to isolate a simpler MRE. Dev guide for building Bokeh docs is here: 

https://docs.bokeh.org/en/latest/docs/dev_guide/documentation.html#setting-up-and-building-bokeh-s-documentation

environment:

```
pydata-sphinx-theme       0.9.0                    pypi_0    pypi
sphinx                    5.3.0                    pypi_0    pypi
sphinx-codeautolink       0.12.1                   pypi_0    pypi
sphinx-copybutton         0.5.0                    pypi_0    pypi
sphinx-design             0.3.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sphinxext-opengraph       0.7.2                    pypi_0    pypi
```

### Patch? 

Changing the condition in `resolve.py` to exclude `type` allows the build to complete "successfully":
```
        if isclass(previous.value) and previous.value is not type and cursor.location not in inventory:
```

however then there are hundreds of other warnings, so this does not seem like a complete solution:

```
.. autolink-examples:: bokeh.plotting.figure.ref :collapse:.
None:4:<autosummary>:1: ERROR: Error in "autolink-examples" directive:
maximum 1 argument(s) allowed, 2 supplied.

.. autolink-examples:: bokeh.plotting.figure.plot :collapse:.
None:4:<autosummary>:1: ERROR: Error in "autolink-examples" directive:
maximum 1 argument(s) allowed, 2 supplied.

.. autolink-examples:: bokeh.plotting.figure.coordinates :collapse:.
/Users/bryan/work/bokeh/src/bokeh/plotting/_figure.py:docstring of bokeh.plotting._figure.figure:1: WARNING: Explicit markup ends without a blank line; unexpected unindent.
```
Without auto-link extension the doc build is 100% warning clean.

**Comment by bryevdv** [comment]
Additionally when the "successful" build finishes, some methods are not linked, e.g. the inherited members of `figure`:
<img width="371" alt="Screenshot 2022-11-28 at 19 31 12" src="https://user-images.githubusercontent.com/1078448/204432027-6660b60b-9998-4177-83df-d949eacc54ed.png">

I'm not sure if this is related or not, these methods all have an extensive decorator to derive much of their functionality from a declarative spec. Perhaps that is interfering.

**Comment by felix-hilden** [comment]
Thanks for submitting the issue and debugging! First, for the easier stuff:

### autolink-examples
Please try:
```rst
.. autolink-examples:: function
   :collapse:
```
instead of having it on a single line. We only expect one argument in the directive, and the "collapse" is considered one if on the same line, rather than being an option.

### methods with no links
We do support linking inherited methods ([test def](https://github.com/felix-hilden/sphinx-codeautolink/blob/master/tests/extension/ref/ref_inherited.txt), [test src](https://github.com/felix-hilden/sphinx-codeautolink/blob/master/tests/extension/src/test_project/__init__.py#L49)). It's most likely a matter of either not finding the method in the inventory (i.e. no ref in autodoc) or the function not being accessible at import.

### type error
I'll look into this in more detail later 👍

**Comment by bryevdv** [comment]
Hi @felix-hilden thanks for the reply, a couple of comments:

> It's most likely a matter of either not finding the method in the inventory (i.e. no ref in autodoc)

How can I verify this? In the built docs, the (inherited) methods do show up in `autoclasstoc`

<img width="401" alt="Screenshot 2022-11-29 at 08 31 45" src="https://user-images.githubusercontent.com/1078448/204587368-4d90ff1c-59bf-4503-8e72-8aa3817b891e.png">

And  in particular `scatter` is in this list further down. The base class (`GlyphAPI` in this case) is not user-facing, so it is not itself explicitly included in the docs anywhere, could that be the issue? 

I will try the [autodoc_inject](https://sphinx-codeautolink.readthedocs.io/en/latest/reference.html#confval-codeautolink_autodoc_inject) suggestion and report back.

**Comment by felix-hilden** [comment]
That's good to know, thanks 👍 Just to set some expectations, I'm unfortunately personally quite busy for a few weeks. I hope to get to this before Christmas though. Surely 😅 

The inventory is generated by Sphinx, and available in the build folder. For example Bokeh's inventory is [here](https://docs.bokeh.org/en/latest/inv.obj). Sphinx reads it [here](https://github.com/sphinx-doc/sphinx/blob/cc314f13e8a98393ab018d83d8957a724a6f338a/sphinx/util/inventory.py#L74). It's generated and passed around during the build in codeautolink [here](https://github.com/felix-hilden/sphinx-codeautolink/blob/master/src/sphinx_codeautolink/extension/__init__.py#L150). So either that, or our name resolver not being up to par!

**Comment by bryevdv** [comment]
@felix-hilden thanks for the details, I will try to dig more into the inventory. Also FYI I we are not yet using `sphinx-codeautolink`, it's something I would very much like to add but I'd say it's a 2023Q1 thing at the earliest, so there's no huge time pressure on my account! (There's also a feature that would take auto code linking from nice to *really, really nice* for Bokeh specifically, that I could potentially work on with some guidance, but I'll open separate issue for that later)

**Comment by felix-hilden** [comment]
Hi! Sorry for dropping this for such a long time. Are you still interested in adding this in?

I believe `__mro__` should be a safer way of getting the class hierarchy, because `type` seems to have a special implementation of `.mro()` different from other objects. But we'll have to go deeper into Bokeh to know what exactly was causing it.

**Comment by felix-hilden** [comment]
Do you still have the branch that you tried? I can try to build the docs with that and see what's up. Otherwise I think it'd be best to start from scratch and try to introduce things gradually and see what we get!

**Comment by bryevdv** [comment]
I'm sure I don't still have the branch, and we have also since removed `autoclasstoc` for now as well, since it was exploding our build times. Probably best to start from scratch with the current state.

**Comment by felix-hilden** [comment]
Okay, I did not succeed in building the documentation. I hit multiple weird bumps, the latest of which was a Flask server starting and blocking in the middle of the documentation build. I think I'd rather guide you through it if that's alright. (I really gotta get off Windows soon too, this was just unnecessarily painful...)

Given a working docs build, if you simply add the library into requirements and as an extension, are some examples linked at least? (maybe you'll have to install from main with git to get the `type` fix)
