### ISSUE TITLE
Error in create_references() introduced in v0.14

### ISSUE THREAD

**Issue by hakonanes** [felix-hilden/sphinx-codeautolink#134]
First of all, thanks a lot for this nice project! It makes navigating documentation simpler and more intuitive.

### Issue
The latest build of my project with sphinx-codeautolink as an extension failed on Read The Docs with v0.14 of sphinx-codeautolink, while it passed with v0.13.2. I'm not qualified to tell what went wrong. Here's the bottom part of the error message:

```python
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/__init__.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/__init__.py", line 179, in create_references
    self.filter_and_resolve(transforms, skipped, doc)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/__init__.py", line 203, in filter_and_resolve
    key = resolve_location(name, self.inventory)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/resolve.py", line 24, in resolve_location
    call_value(cursor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/resolve.py", line 109, in call_value
    cursor.value = get_return_annotation(cursor.value)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/resolve.py", line 141, in get_return_annotation
    f"Unable to follow return annotation of {fully_qualified_name(func)}."
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx_codeautolink/extension/resolve.py", line 149, in fully_qualified_name
    return thing.__module__ + "." + thing.__qualname__
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/cmd/build.py", line 281, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/application.py", line 347, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 310, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 326, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/builders/__init__.py", line 439, in read
    for retval in self.events.emit('env-updated', self.env):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kikuchipy/envs/598/lib/python3.10/site-packages/sphinx/events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <bound method SphinxCodeAutoLink.create_references of <sphinx_codeautolink.extension.SphinxCodeAutoLink object at 0x7f3b2e519cf0>> for event 'env-updated' threw an exception (exception: unsupported operand type(s) for +: 'NoneType' and 'str')

Extension error (sphinx_codeautolink.extension):
Handler <bound method SphinxCodeAutoLink.create_references of <sphinx_codeautolink.extension.SphinxCodeAutoLink object at 0x7f3b2e519cf0>> for event 'env-updated' threw an exception (exception: unsupported operand type(s) for +: 'NoneType' and 'str')
```

Link to the full build: https://readthedocs.org/projects/kikuchipy/builds/19310823/.

### Expected behavior
Build without issues, as with v0.13.2.

### Steps to reproduce
I'm sorry, but all I can provide at the moment is the above build log. I hope it's enough.

**Comment by Zeitsperre** [comment]
I'm seeing something similar in my build on ReadTheDocs: https://readthedocs.org/projects/xclim/builds/19319216/

**Comment by felix-hilden** [comment]
Thanks for submitting this! Indeed I included some information in our error messages, and seems that the assumption that `__module__` is available for everything was incorrect. I'll debug a bit an hopefully resolve this soon.

**Comment by hakonanes** [comment]
Sounds good. No rush from my end as v0.13.2 works fine.

**Comment by felix-hilden** [comment]
Alright, it seems that at least the builtin (non-overrided) dunders of a class don't have a `__module__`. Not sure when it would be `None`, but I think since in this case the output is only informative, I'll make a "safe" version to get at least some debug information. We'll leave the raw access to parsing itself, where I'd still like to receive an error instead of it propagating to some later part of the program.

**Comment by felix-hilden** [comment]
Ah, I *knew* this was familiar: #61. So `None` values definitely seen as well.

**Comment by felix-hilden** [comment]
Now released, lemme know if there are any issues!
