### ISSUE TITLE
TypeError thrown by follow_return_annotation

### ISSUE THREAD

**Issue by rsokl** [felix-hilden/sphinx-codeautolink#72]
The following `TypeError` occurs when the extension is parsing `hydra_zen.typing`. 

```
Traceback (most recent call last):ence
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\__init__.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\__init__.py", line 126, in generate_backref_tables
    self.once_on_doctree_resolved(app)
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\__init__.py", line 140, in once_on_doctree_resolved
    self.filter_and_resolve(transforms, app)
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\__init__.py", line 153, in filter_and_resolve    
    key = resolve_location(name, inventory)
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\resolve.py", line 13, in resolve_location        
    new = locate_type(tuple(comps), inventory, ends_with_call=True)
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\resolve.py", line 64, in locate_type
    location = follow_return_annotation(value)
  File "c:\users\ryan soklaski\sphinx-codeautolink\src\sphinx_codeautolink\extension\resolve.py", line 77, in follow_return_annotation
    if origin is Union and len(args) == 2 and isinstance(None, args[1]):
  File "C:\Users\Ryan Soklaski\Anaconda3\envs\hydra-zen\lib\typing.py", line 769, in __instancecheck__
    return self.__subclasscheck__(type(obj))
  File "C:\Users\Ryan Soklaski\Anaconda3\envs\hydra-zen\lib\typing.py", line 777, in __subclasscheck__
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

```
Extension error (sphinx_codeautolink.extension):
Handler <bound method SphinxCodeAutoLink.generate_backref_tables of <sphinx_codeautolink.extension.SphinxCodeAutoLink object at 0x00000241D5BBA580>> for event 'doctree-resolved' threw an exception (exception: Subscripted generics cannot be used with class and instance checks (in document `C:\Users\Ryan Soklaski\hydra-zen\docs\source\api_reference.rst`))
```

I expect that this is caused by

```python
SupportedPrimitive = Union[
    _SupportedPrimitive,
    Dict[_HydraPrimitive, "SupportedPrimitive"],
    Counter[_HydraPrimitive],
    Set["SupportedPrimitive"],
    FrozenSet["SupportedPrimitive"],
    Deque["SupportedPrimitive"],
    List["SupportedPrimitive"],
    Tuple["SupportedPrimitive", ...],
]
```

for which the args are subscripted generics.

**Comment by felix-hilden** [comment]
Thanks for the report, I'll check this out tomorrow!

**Comment by felix-hilden** [comment]
This check fails only if the number of "Union" arguments is exactly 2 due to "and" short circuiting. So it must be some similar type in your code base. But in any case, I could reproduce it. And it highlights a wider problem in our assumption on that line. Even string type hints would fail the build, because they cannot be used in instance checks as the type. Let's fix all that.

**Comment by felix-hilden** [comment]
Let me know if there still are issues though! I'll wait a bit for the next release to hopefully get other things in too.
